export default {
  emaSignal: null,
  dmi5m: {
    prevDmi: null,
    dmiMdiSignal: 0,
    adxSignal: 0,
    mdiSignal: 0,
    adxBuySignalVolume: 0,
    adxSellSignalVolume: 0,
    willPriceGrow: false,
    trend: null,
  },
  dmi1h: {
    prevDmi: null,
    dmiMdiSignal: 0,
    adxSignal: 0,
    mdiSignal: 0,
    adxBuySignalVolume: 0,
    adxSellSignalVolume: 0,
    willPriceGrow: false,
    trend: null,
  },
  dmi1m: {
    prevDmi: null,
    dmiMdiSignal: 0,
    adxSignal: 0,
    mdiSignal: 0,
    adxBuySignalVolume: 0,
    adxSellSignalVolume: 0,
    willPriceGrow: false,
    trend: null,
  },
  rsi1m: {
    rsiValue: null,
    prevRsi: null,
    sellNow: false,
    buyNow: false,
  },
  slow1mEMA: 0,
  middle1mEMA: 0,
  fast1mEMA: 0,
  slow5mEMA: 0,
  middle5mEMA: 0,
  fast5mEMA: 0,
  slow1hEMA: 0,
  middle1hEMA: 0,
  fast1hEMA: 0,
  slow15mEMA: 0,
  middle15mEMA: 0,
  fast15mEMA: 0,
  summaryEMABuySignal: false,
};
