name: Build

on:
  push:
    branches:
      - master
      - deploy

    paths:
      - .github/workflows/build.yaml
      - package.json
      - Dockerfile
      - package-lock.json
      - src/**

concurrency:
  group: binance-bot-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - uses: actions/checkout@v3

      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Setup cache
      - name: ⚡️ Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: 🔑 Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🐳 Docker build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: fictionaldev/binance-bot
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: 🚚 Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache


  deploy:
    needs:
      - build
    uses: ./.github/workflows/deploy.yaml
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      ENV_TELEGRAM_API_URL: ${{ secrets.ENV_TELEGRAM_API_URL }}
      ENV_APIKEY: ${{ secrets.ENV_APIKEY }}
      ENV_APISECRET: ${{ secrets.ENV_APISECRET }}
      ENV_DB_URL: ${{ secrets.ENV_DB_URL }}
